spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbproject
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhj192837680715
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy